name: Build (Ubuntu 24.04)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake ninja-build \
          libocct-draw-dev libocct-visualization-dev libocct-ocaf-dev libocct-modeling-data-dev \
          libocct-modeling-algorithms-dev libocct-foundation-dev libocct-data-exchange-dev \
          libgl-dev libegl-dev \
          tcllib tklib tcl-dev tk-dev \
          libtbb-dev \
          xvfb
    - name: Configure project
      run: |
        mkdir "build"
        cmake -G Ninja -S . -B "./build"
    - name: Build project
      run: |
        cmake --build "./build" --config Release
    - name: Run tests
      run: |
        pushd ./build
        xvfb-run ./occt-ais-offscreen/occt-ais-offscreen -noopen
        popd
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: occt-hello-ubuntu
        path: ./build/image.png
